### ISSUE TITLE
[Please change the title]

### ISSUE THREAD

**Issue by anubha-v-ardhan** [anubha-v-ardhan/test-twitter-together#11]
A YAML payload will follow.

    ```yaml
    name: Hello World
    id: 100
    description: A simple hello world example
    tags:
      - good first issue
      - needs triage
      - bug
    ```
